apiVersion: v1
kind: Pod
metadata:
  name: debian-debug
  namespace: default
  annotations:
    injector.tumblr.com/request: test1
spec:
  containers:
  - image: debian:jessie
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: debian-debug
  restartPolicy: Never
